### ISSUE TITLE
Atualização ?

### ISSUE THREAD

**Issue by celibertojr** [pedrosolbm/RoboCupSoccerSim-Tools#1]
Está atualizado ? Gostaria de apontar esse script para ajudar meus alunos a instalar o Robocup 2D, quando eu usei não encontrei problemas, mas como faz um tempinho e não consegui tempo de testa-lo novamente, gostaria de saber se fizeram alguma atualização ? obrigado.

**Comment by hebertluiz** [comment]
Não foi feita nenhuma alteração, acredito que esteja funcional sim. 
Testarei assim que possível se alguma novidade nas novas versões do Ubuntu causaram problemas.
